### ISSUE TITLE
about the minimum GPU memory required

### ISSUE THREAD

**Issue by amiltonwong** [hszhao/SAN#1]
Hi, @hszhao ,

Thanks for releasing the package. I'd rather to know the minimum requirement on GPU memory. Is a GPU with 12GB enough to run the training?

THX!

**Comment by hszhao** [comment]
Hi, our experiments on ImageNet (crop size as 224x224, batch size as 256) are conducted on a server with 8 x Quadro RTX 6000 (24G). Detailed memory usage for each GPU is listed below:
Pairwise-SAN10/15/19: 13091/17259/20781MiB.
Patchwise-SAN10/15/19: 9007/11479/13493MiB.
