### ISSUE TITLE
can this network be deployed on cpus?

### ISSUE THREAD

**Issue by iamZe** [hszhao/SAN#2]
thanks.

**Comment by bluesky314** [comment]
+1

**Comment by bluesky314** [comment]
@hszhao Any reply to this? I tried training on cpu and it did not work.

**Comment by hszhao** [comment]
Hi, currently only GPU version is supported as CPU training is much slower when compared to GPU training. To enable CPU training, you need to remove the CUDA part in 'tool/train.py' and modify the operators in 'model/san.py'.
