### ISSUE TITLE
AggregationRefpadBackward failed

### ISSUE THREAD

**Issue by liangkangzheng** [hszhao/SAN#3]
Hi Zhao,
when I test image of which height != width, errors occurred.
lib/sa/functions/aggregation_refpad.py
n, c_x, c_w, in_height, in_width = 2, 8, 4, 24, 44

RuntimeError: Function AggregationRefpadBackward returned an invalid gradient at index 0 - got [2, 8, 28, 44] but expected shape compatible with [2, 8, 24, 44]

Looking forward to your response!
LIANG

**Comment by hszhao** [comment]
Thanks!
It is due to four typos in the backward path. 
The issue has been addressed in the repo.
