### ISSUE TITLE
What calculations are performed by the Aggregation function?

### ISSUE THREAD

**Issue by shimopino** [hszhao/SAN#4]
Thank you for your great work!

When I run the SAM module on PatchWise-Attention (sa_type=1) for verification, the input tensors of the Aggregation function has the following shape.

<img src="https://latex.codecogs.com/gif.latex?x_{3}:&space;{\left[B,&space;\dfrac{C}{r_{2}},&space;H,&space;W&space;\right]}" >

<img src="https://latex.codecogs.com/gif.latex?w:{\left[B,&space;\dfrac{C}{r_{2}\times&space;\text{shaped\_kernel}},&space;kernel\_size^{2},&space;H\times&space;W&space;\right]}" >

In the paper, it says that the outputs of the streams are aggregated via a Hadamard product. 

Would you like to tell me what operations are performed on the tensors of these different shapes to perform a Hadamard product?

**Comment by hszhao** [comment]
Hi, for a local footprint (e.g., KxK) in each position, the tensor's shape is C/r_2xKxK, the learned attention weights w is C/r_2/share_planesxKxK. And 'share_planes' number of channels share the same attention weight. We do Hadamard product and spatial aggregation to generate the output for this position.
