### ISSUE TITLE
Robustness to Adversarial Attacks

### ISSUE THREAD

**Issue by leodmel** [hszhao/SAN#6]
Hi, could you kindly provide the implementation details of how to obtain the results demonstrated in Table 10 in your paper, i.e., the part on robustness to adversarial attacks? I have tried several different targeted PGD methods, but still I found my results are quite different from yours.

**Comment by hszhao** [comment]
Hi, we use the 'foolbox' to generate the adversarial samples. Thanks.
https://foolbox.readthedocs.io/en/stable
